//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Cuyahoga {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Cuyahoga.ValidationMessages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category description must be between 1 and 255 characters.
        /// </summary>
        internal static string CategoryDescriptionValidatorLength {
            get {
                return ResourceManager.GetString("CategoryDescriptionValidatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category name must be between 1 and 100 characters.
        /// </summary>
        internal static string CategoryNameValidatorLength {
            get {
                return ResourceManager.GetString("CategoryNameValidatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category name may not be empty.
        /// </summary>
        internal static string CategoryNameValidatorNonEmpty {
            get {
                return ResourceManager.GetString("CategoryNameValidatorNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category must be connected to a site.
        /// </summary>
        internal static string CategorySiteValidatorNonEmpty {
            get {
                return ResourceManager.GetString("CategorySiteValidatorNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date/time.
        /// </summary>
        internal static string ContentItemPublishedAtValidatorDateTime {
            get {
                return ResourceManager.GetString("ContentItemPublishedAtValidatorDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date/time.
        /// </summary>
        internal static string ContentItemPublishedUntilValidatorDateTime {
            get {
                return ResourceManager.GetString("ContentItemPublishedUntilValidatorDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish date must be before Publish end date.
        /// </summary>
        internal static string ContentItemPublishedUntilValidatorGreaterThanPublishedAt {
            get {
                return ResourceManager.GetString("ContentItemPublishedUntilValidatorGreaterThanPublishedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The summary must be between 1 and 255 characters.
        /// </summary>
        internal static string ContentItemSummaryValidatorLength {
            get {
                return ResourceManager.GetString("ContentItemSummaryValidatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title must be between 1 and 100 characters.
        /// </summary>
        internal static string ContentItemTitleValidatorLength {
            get {
                return ResourceManager.GetString("ContentItemTitleValidatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title may not be empty.
        /// </summary>
        internal static string ContentItemTitleValidatorNonEmpty {
            get {
                return ResourceManager.GetString("ContentItemTitleValidatorNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A default culture is required.
        /// </summary>
        internal static string DefaultCultureValidatorNonEmpty {
            get {
                return ResourceManager.GetString("DefaultCultureValidatorNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A default role is required.
        /// </summary>
        internal static string DefaultRoleValidatorNonEmpty {
            get {
                return ResourceManager.GetString("DefaultRoleValidatorNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid e-mail address.
        /// </summary>
        internal static string EmailValidatorEmail {
            get {
                return ResourceManager.GetString("EmailValidatorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address must be between 1 and 100 characters.
        /// </summary>
        internal static string EmailValidatorLength {
            get {
                return ResourceManager.GetString("EmailValidatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address may not be empty.
        /// </summary>
        internal static string EmailValidatorNonEmpty {
            get {
                return ResourceManager.GetString("EmailValidatorNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firstname must be between 1 and 100 characters.
        /// </summary>
        internal static string FirstNameValidatorLength {
            get {
                return ResourceManager.GetString("FirstNameValidatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lastname must be between 1 and 100 characters.
        /// </summary>
        internal static string LastNameValidatorLength {
            get {
                return ResourceManager.GetString("LastNameValidatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta description can contain max. 500 characters.
        /// </summary>
        internal static string MetaDescriptionValidatorLength {
            get {
                return ResourceManager.GetString("MetaDescriptionValidatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta keywords can contain max. 500 characters.
        /// </summary>
        internal static string MetaKeywordsValidatorLength {
            get {
                return ResourceManager.GetString("MetaKeywordsValidatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The culture is required.
        /// </summary>
        internal static string NodeCultureValidatorNonEmpty {
            get {
                return ResourceManager.GetString("NodeCultureValidatorNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link url must be between 1 and 255 characters.
        /// </summary>
        internal static string NodeLinkUrlValidatorLength {
            get {
                return ResourceManager.GetString("NodeLinkUrlValidatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link url is not a valid hyperlink.
        /// </summary>
        internal static string NodeLinkUrlValidatorPattern {
            get {
                return ResourceManager.GetString("NodeLinkUrlValidatorPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The friendly url must be between 1 and 255 characters.
        /// </summary>
        internal static string NodeShortDescriptionValidatorLength {
            get {
                return ResourceManager.GetString("NodeShortDescriptionValidatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The friendly url is required.
        /// </summary>
        internal static string NodeShortDescriptionValidatorNonEmpty {
            get {
                return ResourceManager.GetString("NodeShortDescriptionValidatorNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page title must be between 1 and 255 characters.
        /// </summary>
        internal static string NodeTitleValidatorLength {
            get {
                return ResourceManager.GetString("NodeTitleValidatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page title may not be empty.
        /// </summary>
        internal static string NodeTitleValidatorNonEmpty {
            get {
                return ResourceManager.GetString("NodeTitleValidatorNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password confirmation may not be empty.
        /// </summary>
        internal static string PasswordConfirmationValidatorNonEmpty {
            get {
                return ResourceManager.GetString("PasswordConfirmationValidatorNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain at least 5 characters.
        /// </summary>
        internal static string PasswordValidatorLength {
            get {
                return ResourceManager.GetString("PasswordValidatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password may not be empty.
        /// </summary>
        internal static string PasswordValidatorNonEmpty {
            get {
                return ResourceManager.GetString("PasswordValidatorNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be the same as the confirmation password.
        /// </summary>
        internal static string PasswordValidatorSameAs {
            get {
                return ResourceManager.GetString("PasswordValidatorSameAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The placeholder can contain max. 100 characters.
        /// </summary>
        internal static string PlaceholderValidatorLength {
            get {
                return ResourceManager.GetString("PlaceholderValidatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must be between 1 and 50 characters.
        /// </summary>
        internal static string RoleNameValidatorLength {
            get {
                return ResourceManager.GetString("RoleNameValidatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role name may not be empty.
        /// </summary>
        internal static string RoleNameValidatorNonEmpty {
            get {
                return ResourceManager.GetString("RoleNameValidatorNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A role with this name already exists (possibly in another site).
        /// </summary>
        internal static string RoleNameValidatorNotUnique {
            get {
                return ResourceManager.GetString("RoleNameValidatorNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user must at least have one role.
        /// </summary>
        internal static string RolesValidatorNotEmpty {
            get {
                return ResourceManager.GetString("RolesValidatorNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title must be between 1 and 100 characters.
        /// </summary>
        internal static string SectionTitleValidatorLength {
            get {
                return ResourceManager.GetString("SectionTitleValidatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title may not be empty.
        /// </summary>
        internal static string SectionTitleValidatorNonEmpty {
            get {
                return ResourceManager.GetString("SectionTitleValidatorNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site name must be between 1 and 100 characters.
        /// </summary>
        internal static string SiteNameValidatorLength {
            get {
                return ResourceManager.GetString("SiteNameValidatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site name may not be empty.
        /// </summary>
        internal static string SiteNameValidatorNonEmpty {
            get {
                return ResourceManager.GetString("SiteNameValidatorNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site url must be between 12 and 100 characters.
        /// </summary>
        internal static string SiteUrlValidatorLength {
            get {
                return ResourceManager.GetString("SiteUrlValidatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site url may not be empty.
        /// </summary>
        internal static string SiteUrlValidatorNonEmpty {
            get {
                return ResourceManager.GetString("SiteUrlValidatorNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid site url (must begin with http:// or https://).
        /// </summary>
        internal static string SiteUrlValidatorPattern {
            get {
                return ResourceManager.GetString("SiteUrlValidatorPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template name must be between 1 and 100 characters.
        /// </summary>
        internal static string TemplateNameValidatorLength {
            get {
                return ResourceManager.GetString("TemplateNameValidatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template name may not be empty.
        /// </summary>
        internal static string TemplateNameValidatorNonEmpty {
            get {
                return ResourceManager.GetString("TemplateNameValidatorNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username must be between 1 and 50 characters.
        /// </summary>
        internal static string UserNameValidatorLength {
            get {
                return ResourceManager.GetString("UserNameValidatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username may not be empty.
        /// </summary>
        internal static string UserNameValidatorNonEmpty {
            get {
                return ResourceManager.GetString("UserNameValidatorNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with this username already exists.
        /// </summary>
        internal static string UserNameValidatorNotUnique {
            get {
                return ResourceManager.GetString("UserNameValidatorNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The website url must be between 1 and 100 characters.
        /// </summary>
        internal static string WebsiteValidatorLength {
            get {
                return ResourceManager.GetString("WebsiteValidatorLength", resourceCulture);
            }
        }
    }
}
