//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Cuyahoga.Web.Manager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Cuyahoga.Web.Manager.GlobalResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string ActionLabel {
            get {
                return ResourceManager.GetString("ActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to perform the requested action..
        /// </summary>
        internal static string ActionNotAllowedException {
            get {
                return ResourceManager.GetString("ActionNotAllowedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string ActionsLabel {
            get {
                return ResourceManager.GetString("ActionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string ActivationStatusLabel {
            get {
                return ResourceManager.GetString("ActivationStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string ActiveStatus {
            get {
                return ResourceManager.GetString("ActiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add connection.
        /// </summary>
        internal static string AddConnectionLabel {
            get {
                return ResourceManager.GetString("AddConnectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add section to page.
        /// </summary>
        internal static string AddSectionDialogTitle {
            get {
                return ResourceManager.GetString("AddSectionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add section to page.
        /// </summary>
        internal static string AddSectionLabel {
            get {
                return ResourceManager.GetString("AddSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly.
        /// </summary>
        internal static string AssemblyLabel {
            get {
                return ResourceManager.GetString("AssemblyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached to.
        /// </summary>
        internal static string AttachedToLabel {
            get {
                return ResourceManager.GetString("AttachedToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach section &apos;{0}&apos; to template(s).
        /// </summary>
        internal static string AttachSectionToTemplatesPageTitle {
            get {
                return ResourceManager.GetString("AttachSectionToTemplatesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach to template(s).
        /// </summary>
        internal static string AttachToTemplateLabel {
            get {
                return ResourceManager.GetString("AttachToTemplateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while authenticating the user..
        /// </summary>
        internal static string AuthenticationException {
            get {
                return ResourceManager.GetString("AuthenticationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string AuthorLabel {
            get {
                return ResourceManager.GetString("AuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a module from the list below and drag it to a content placeholder in the template to create a new section..
        /// </summary>
        internal static string AvailableModulesHint {
            get {
                return ResourceManager.GetString("AvailableModulesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available modules.
        /// </summary>
        internal static string AvailableModulesLabel {
            get {
                return ResourceManager.GetString("AvailableModulesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BackLabel {
            get {
                return ResourceManager.GetString("BackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to page list.
        /// </summary>
        internal static string BackToPageListLabel {
            get {
                return ResourceManager.GetString("BackToPageListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base path.
        /// </summary>
        internal static string BasePathLabel {
            get {
                return ResourceManager.GetString("BasePathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string BrowseButtonLabel {
            get {
                return ResourceManager.GetString("BrowseButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string CategoriesLabel {
            get {
                return ResourceManager.GetString("CategoriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category {0} is created successfully..
        /// </summary>
        internal static string CategoryCreatedMessage {
            get {
                return ResourceManager.GetString("CategoryCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category {0} is deleted successfully..
        /// </summary>
        internal static string CategoryDeletedMessage {
            get {
                return ResourceManager.GetString("CategoryDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete the category because it has child categories..
        /// </summary>
        internal static string CategoryHasChildCategoriesException {
            get {
                return ResourceManager.GetString("CategoryHasChildCategoriesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete the category because it contains content items..
        /// </summary>
        internal static string CategoryHasContentItemsException {
            get {
                return ResourceManager.GetString("CategoryHasContentItemsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category {0} is updated successfully..
        /// </summary>
        internal static string CategoryUpdatedMessage {
            get {
                return ResourceManager.GetString("CategoryUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ChangePasswordLabel {
            get {
                return ResourceManager.GetString("ChangePasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a template.
        /// </summary>
        internal static string ChooseTemplateOption {
            get {
                return ResourceManager.GetString("ChooseTemplateOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseLabel {
            get {
                return ResourceManager.GetString("CloseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string CommentLabel {
            get {
                return ResourceManager.GetString("CommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string CommentsLabel {
            get {
                return ResourceManager.GetString("CommentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string ConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection for action {0} was added succesfully..
        /// </summary>
        internal static string ConnectionAddedMessage {
            get {
                return ResourceManager.GetString("ConnectionAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection for action {0} is removed successfully..
        /// </summary>
        internal static string ConnectionDeletedMessage {
            get {
                return ResourceManager.GetString("ConnectionDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to section.
        /// </summary>
        internal static string ConnectToLabel {
            get {
                return ResourceManager.GetString("ConnectToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CopyButtonLabel {
            get {
                return ResourceManager.GetString("CopyButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected items to.
        /// </summary>
        internal static string CopySelectedItemsTo {
            get {
                return ResourceManager.GetString("CopySelectedItemsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy templates.
        /// </summary>
        internal static string CopyTemplatesLabel {
            get {
                return ResourceManager.GetString("CopyTemplatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string CreateButtonLabel {
            get {
                return ResourceManager.GetString("CreateButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new category.
        /// </summary>
        internal static string CreateCategoryLabel {
            get {
                return ResourceManager.GetString("CreateCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new directory.
        /// </summary>
        internal static string CreateDirectoryLabel {
            get {
                return ResourceManager.GetString("CreateDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new role.
        /// </summary>
        internal static string CreateRoleLabel {
            get {
                return ResourceManager.GetString("CreateRoleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create section.
        /// </summary>
        internal static string CreateSectionLabel {
            get {
                return ResourceManager.GetString("CreateSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create shared section.
        /// </summary>
        internal static string CreateSharedSectionLabel {
            get {
                return ResourceManager.GetString("CreateSharedSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new site.
        /// </summary>
        internal static string CreateSiteLabel {
            get {
                return ResourceManager.GetString("CreateSiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create user.
        /// </summary>
        internal static string CreateUserLabel {
            get {
                return ResourceManager.GetString("CreateUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Css.
        /// </summary>
        internal static string CssLabel {
            get {
                return ResourceManager.GetString("CssLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        internal static string CultureLabel {
            get {
                return ResourceManager.GetString("CultureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current directory.
        /// </summary>
        internal static string CurrentDirectoryLabel {
            get {
                return ResourceManager.GetString("CurrentDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties full-text index for current site.
        /// </summary>
        internal static string CurrentIndexProperties {
            get {
                return ResourceManager.GetString("CurrentIndexProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuyahoga Site Manager.
        /// </summary>
        internal static string CuyahogaSiteManagerLabel {
            get {
                return ResourceManager.GetString("CuyahogaSiteManagerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string DashboardPageTitle {
            get {
                return ResourceManager.GetString("DashboardPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Modified.
        /// </summary>
        internal static string DateModifiedLabel {
            get {
                return ResourceManager.GetString("DateModifiedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default culture.
        /// </summary>
        internal static string DefaultCultureLabel {
            get {
                return ResourceManager.GetString("DefaultCultureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default meta description.
        /// </summary>
        internal static string DefaultMetaDescriptionLabel {
            get {
                return ResourceManager.GetString("DefaultMetaDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default meta keywords.
        /// </summary>
        internal static string DefaultMetaKeywordsLabel {
            get {
                return ResourceManager.GetString("DefaultMetaKeywordsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default placeholder in the default template.
        /// </summary>
        internal static string DefaultPlaceholderLabel {
            get {
                return ResourceManager.GetString("DefaultPlaceholderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default role for authenticated users.
        /// </summary>
        internal static string DefaultRoleLabel {
            get {
                return ResourceManager.GetString("DefaultRoleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults.
        /// </summary>
        internal static string DefaultsLabel {
            get {
                return ResourceManager.GetString("DefaultsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default template.
        /// </summary>
        internal static string DefaultTemplateLabel {
            get {
                return ResourceManager.GetString("DefaultTemplateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteButtonLabel {
            get {
                return ResourceManager.GetString("DeleteButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the current link.
        /// </summary>
        internal static string DeleteLinkLabel {
            get {
                return ResourceManager.GetString("DeleteLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the current page.
        /// </summary>
        internal static string DeletePageLabel {
            get {
                return ResourceManager.GetString("DeletePageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop a section in this box to remove it from the page.
        /// </summary>
        internal static string DeleteSectionBoxHint {
            get {
                return ResourceManager.GetString("DeleteSectionBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the section or only detach it from the page?.
        /// </summary>
        internal static string DeleteSectionChoiceLabel {
            get {
                return ResourceManager.GetString("DeleteSectionChoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, delete section.
        /// </summary>
        internal static string DeleteSectionConfirmLabel {
            get {
                return ResourceManager.GetString("DeleteSectionConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected items.
        /// </summary>
        internal static string DeleteSelectedItems {
            get {
                return ResourceManager.GetString("DeleteSelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete yourself..
        /// </summary>
        internal static string DeleteYourselfNotAllowedException {
            get {
                return ResourceManager.GetString("DeleteYourselfNotAllowedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout of the current page.
        /// </summary>
        internal static string DesignCurrentPageLabel {
            get {
                return ResourceManager.GetString("DesignCurrentPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout of page &apos;{0}&apos;.
        /// </summary>
        internal static string DesignPagePageTitle {
            get {
                return ResourceManager.GetString("DesignPagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just detach the section from the page.
        /// </summary>
        internal static string DetachSectionConfirmLabel {
            get {
                return ResourceManager.GetString("DetachSectionConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory {0} is created successfully..
        /// </summary>
        internal static string DirectoryCreatedMessage {
            get {
                return ResourceManager.GetString("DirectoryCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit category.
        /// </summary>
        internal static string EditCategoryPageTitle {
            get {
                return ResourceManager.GetString("EditCategoryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit content.
        /// </summary>
        internal static string EditContentDialogTitle {
            get {
                return ResourceManager.GetString("EditContentDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit content.
        /// </summary>
        internal static string EditContentLabel {
            get {
                return ResourceManager.GetString("EditContentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditLabel {
            get {
                return ResourceManager.GetString("EditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit layout.
        /// </summary>
        internal static string EditLayoutLabel {
            get {
                return ResourceManager.GetString("EditLayoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit role.
        /// </summary>
        internal static string EditRolePageTitle {
            get {
                return ResourceManager.GetString("EditRolePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles that are allowed to edit the content.
        /// </summary>
        internal static string EditRolesLabel {
            get {
                return ResourceManager.GetString("EditRolesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit template.
        /// </summary>
        internal static string EditTemplatePageTitle {
            get {
                return ResourceManager.GetString("EditTemplatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        internal static string EditUserPageTitle {
            get {
                return ResourceManager.GetString("EditUserPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password may not be empty..
        /// </summary>
        internal static string EmptyUsernameOrPassword {
            get {
                return ResourceManager.GetString("EmptyUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The files and/or directories are copied to {0}..
        /// </summary>
        internal static string FilesDirectoriesCopiedMessage {
            get {
                return ResourceManager.GetString("FilesDirectoriesCopiedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The files and/or directories are deleted successfully..
        /// </summary>
        internal static string FilesDirectoriesDeletedMessage {
            get {
                return ResourceManager.GetString("FilesDirectoriesDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The files and/or directories are moved to {0}..
        /// </summary>
        internal static string FilesDirectoriesMovedMessage {
            get {
                return ResourceManager.GetString("FilesDirectoriesMovedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is saved on the server as {0}..
        /// </summary>
        internal static string FileUploadSuccessMessage {
            get {
                return ResourceManager.GetString("FileUploadSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string FilterButtonLabel {
            get {
                return ResourceManager.GetString("FilterButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory index files.
        /// </summary>
        internal static string FullTextIndexDirectoryLabel {
            get {
                return ResourceManager.GetString("FullTextIndexDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full-text index was rebuilt successfully..
        /// </summary>
        internal static string FullTextIndexRebuildMessage {
            get {
                return ResourceManager.GetString("FullTextIndexRebuildMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string GeneralLabel {
            get {
                return ResourceManager.GetString("GeneralLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in all sites.
        /// </summary>
        internal static string GlobalSearchLabel {
            get {
                return ResourceManager.GetString("GlobalSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not active.
        /// </summary>
        internal static string InactiveStatus {
            get {
                return ResourceManager.GetString("InactiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of documents in index.
        /// </summary>
        internal static string IndexSizeLabel {
            get {
                return ResourceManager.GetString("IndexSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation status.
        /// </summary>
        internal static string InstallationStatusLabel {
            get {
                return ResourceManager.GetString("InstallationStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        internal static string InstalledStatus {
            get {
                return ResourceManager.GetString("InstalledStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed (upgrade available).
        /// </summary>
        internal static string InstalledUpgradeStatus {
            get {
                return ResourceManager.GetString("InstalledUpgradeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string InstallLabel {
            get {
                return ResourceManager.GetString("InstallLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid .ascx file location in package. Make sure the .ascx files are in the root of the package..
        /// </summary>
        internal static string InvalidAscxLocationException {
            get {
                return ResourceManager.GetString("InvalidAscxLocationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid .css file location in package. Make sure the .css files are in the &apos;css&apos; subdirectory..
        /// </summary>
        internal static string InvalidCssLocationException {
            get {
                return ResourceManager.GetString("InvalidCssLocationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid directory found in package. Only &apos;Images&apos; and &apos;Css&apos; are allowed..
        /// </summary>
        internal static string InvalidDirectoryInPackageFoundException {
            get {
                return ResourceManager.GetString("InvalidDirectoryInPackageFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file extension found in package..
        /// </summary>
        internal static string InvalidExtensionFoundException {
            get {
                return ResourceManager.GetString("InvalidExtensionFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password. Make sure it has at least 5 characters..
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username-password combination..
        /// </summary>
        internal static string InvalidUsernamePassword {
            get {
                return ResourceManager.GetString("InvalidUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is not a valid .zip archive.
        /// </summary>
        internal static string InvalidZipFileMessage {
            get {
                return ResourceManager.GetString("InvalidZipFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string IsActiveLabel {
            get {
                return ResourceManager.GetString("IsActiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is attached.
        /// </summary>
        internal static string IsAttachedLabel {
            get {
                return ResourceManager.GetString("IsAttachedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is global.
        /// </summary>
        internal static string IsGlobalLabel {
            get {
                return ResourceManager.GetString("IsGlobalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to go to the administration of the site.
        /// </summary>
        internal static string JumpToSiteAdminLabel {
            get {
                return ResourceManager.GetString("JumpToSiteAdminLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last login from.
        /// </summary>
        internal static string LastLoginfromLabel {
            get {
                return ResourceManager.GetString("LastLoginfromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last login.
        /// </summary>
        internal static string LastLoginLabel {
            get {
                return ResourceManager.GetString("LastLoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified.
        /// </summary>
        internal static string LastModifiedLabel {
            get {
                return ResourceManager.GetString("LastModifiedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link {0} was created successfully..
        /// </summary>
        internal static string LinkCreatedMessage {
            get {
                return ResourceManager.GetString("LinkCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link {0} was deleted successfully..
        /// </summary>
        internal static string LinkDeletedMessage {
            get {
                return ResourceManager.GetString("LinkDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link properties.
        /// </summary>
        internal static string LinkPropertiesLabel {
            get {
                return ResourceManager.GetString("LinkPropertiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link properties are updated..
        /// </summary>
        internal static string LinkPropertiesUpdatedMessage {
            get {
                return ResourceManager.GetString("LinkPropertiesUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link target.
        /// </summary>
        internal static string LinkTargetLabel {
            get {
                return ResourceManager.GetString("LinkTargetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link title.
        /// </summary>
        internal static string LinkTitleLabel {
            get {
                return ResourceManager.GetString("LinkTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link url.
        /// </summary>
        internal static string LinkUrlLabel {
            get {
                return ResourceManager.GetString("LinkUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load on startup.
        /// </summary>
        internal static string LoadOnStartupLabel {
            get {
                return ResourceManager.GetString("LoadOnStartupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as.
        /// </summary>
        internal static string LoggedInAsLabel {
            get {
                return ResourceManager.GetString("LoggedInAsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginButtonLabel {
            get {
                return ResourceManager.GetString("LoginButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LogoutButtonLabel {
            get {
                return ResourceManager.GetString("LogoutButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage categories.
        /// </summary>
        internal static string ManageCategoriesPageTitle {
            get {
                return ResourceManager.GetString("ManageCategoriesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage content current page.
        /// </summary>
        internal static string ManageContentCurrentPageLabel {
            get {
                return ResourceManager.GetString("ManageContentCurrentPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage page content on &apos;{0}&apos;.
        /// </summary>
        internal static string ManageContentPageTitle {
            get {
                return ResourceManager.GetString("ManageContentPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage files.
        /// </summary>
        internal static string ManageFilesPageTitle {
            get {
                return ResourceManager.GetString("ManageFilesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage modules.
        /// </summary>
        internal static string ManageModulesPageTitle {
            get {
                return ResourceManager.GetString("ManageModulesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage pages.
        /// </summary>
        internal static string ManagePagesPageTitle {
            get {
                return ResourceManager.GetString("ManagePagesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage permissions.
        /// </summary>
        internal static string ManagePermissionsLabel {
            get {
                return ResourceManager.GetString("ManagePermissionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string ManagerMenuCategories {
            get {
                return ResourceManager.GetString("ManagerMenuCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string ManagerMenuContent {
            get {
                return ResourceManager.GetString("ManagerMenuContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string ManagerMenuDashboard {
            get {
                return ResourceManager.GetString("ManagerMenuDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string ManagerMenuFiles {
            get {
                return ResourceManager.GetString("ManagerMenuFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        internal static string ManagerMenuModules {
            get {
                return ResourceManager.GetString("ManagerMenuModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        internal static string ManagerMenuPages {
            get {
                return ResourceManager.GetString("ManagerMenuPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage roles.
        /// </summary>
        internal static string ManagerMenuRoles {
            get {
                return ResourceManager.GetString("ManagerMenuRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server settings.
        /// </summary>
        internal static string ManagerMenuServer {
            get {
                return ResourceManager.GetString("ManagerMenuServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared content.
        /// </summary>
        internal static string ManagerMenuSharedContent {
            get {
                return ResourceManager.GetString("ManagerMenuSharedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site settings.
        /// </summary>
        internal static string ManagerMenuSite {
            get {
                return ResourceManager.GetString("ManagerMenuSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string ManagerMenuTemplates {
            get {
                return ResourceManager.GetString("ManagerMenuTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users and roles.
        /// </summary>
        internal static string ManagerMenuUsers {
            get {
                return ResourceManager.GetString("ManagerMenuUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage roles.
        /// </summary>
        internal static string ManageRolesPageTitle {
            get {
                return ResourceManager.GetString("ManageRolesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage shared content.
        /// </summary>
        internal static string ManageSharedContentPageTitle {
            get {
                return ResourceManager.GetString("ManageSharedContentPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage site.
        /// </summary>
        internal static string ManageSitePageTitle {
            get {
                return ResourceManager.GetString("ManageSitePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage templates.
        /// </summary>
        internal static string ManageTemplatesPageTitle {
            get {
                return ResourceManager.GetString("ManageTemplatesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        internal static string ManageUsersPageTitle {
            get {
                return ResourceManager.GetString("ManageUsersPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some errors have occured:.
        /// </summary>
        internal static string ModelValidationErrorMessage {
            get {
                return ResourceManager.GetString("ModelValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module {0} was activated successfully..
        /// </summary>
        internal static string ModuleActivatedMessage {
            get {
                return ResourceManager.GetString("ModuleActivatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module {0} was deactivated successfully and will unload at the next application restart. .
        /// </summary>
        internal static string ModuleDeactivatedMessage {
            get {
                return ResourceManager.GetString("ModuleDeactivatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to install this module?.
        /// </summary>
        internal static string ModuleInstallConfirmation {
            get {
                return ResourceManager.GetString("ModuleInstallConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module {0} was installed and activated successfully..
        /// </summary>
        internal static string ModuleInstalledAndActivatedMessage {
            get {
                return ResourceManager.GetString("ModuleInstalledAndActivatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module type.
        /// </summary>
        internal static string ModuleTypeLabel {
            get {
                return ResourceManager.GetString("ModuleTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to uninstall this module?.
        /// </summary>
        internal static string ModuleUninstallConfirmation {
            get {
                return ResourceManager.GetString("ModuleUninstallConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module {0} was uninstalled successfully..
        /// </summary>
        internal static string ModuleUninstalledMessage {
            get {
                return ResourceManager.GetString("ModuleUninstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to upgrade this module?.
        /// </summary>
        internal static string ModuleUpgradeConfirmation {
            get {
                return ResourceManager.GetString("ModuleUpgradeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module {0} was upgraded successfully..
        /// </summary>
        internal static string ModuleUpgradedMessage {
            get {
                return ResourceManager.GetString("ModuleUpgradedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string MoveButtonLabel {
            get {
                return ResourceManager.GetString("MoveButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to move this page under a new parent? Alternatively, you can also make a copy of the page. This will copy the page properties and sections. Note that this will not copy the actual content..
        /// </summary>
        internal static string MoveOrCopyPageDialogText {
            get {
                return ResourceManager.GetString("MoveOrCopyPageDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move or copy page.
        /// </summary>
        internal static string MoveOrCopyPageDialogTitle {
            get {
                return ResourceManager.GetString("MoveOrCopyPageDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to page.
        /// </summary>
        internal static string MoveSectionToPageLabel {
            get {
                return ResourceManager.GetString("MoveSectionToPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected items to.
        /// </summary>
        internal static string MoveSelectedItemsTo {
            get {
                return ResourceManager.GetString("MoveSelectedItemsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new category.
        /// </summary>
        internal static string NewCategoryPageTitle {
            get {
                return ResourceManager.GetString("NewCategoryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new link below the current page.
        /// </summary>
        internal static string NewChildLinkLabel {
            get {
                return ResourceManager.GetString("NewChildLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new page below the current page.
        /// </summary>
        internal static string NewChildPageLabel {
            get {
                return ResourceManager.GetString("NewChildPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New connection for &apos;{0}&apos;.
        /// </summary>
        internal static string NewConnectionPageTitle {
            get {
                return ResourceManager.GetString("NewConnectionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new role.
        /// </summary>
        internal static string NewRolePageTitle {
            get {
                return ResourceManager.GetString("NewRolePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new top-level page.
        /// </summary>
        internal static string NewRootPageLabel {
            get {
                return ResourceManager.GetString("NewRootPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New shared section.
        /// </summary>
        internal static string NewSharedSectionPageTitle {
            get {
                return ResourceManager.GetString("NewSharedSectionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new site.
        /// </summary>
        internal static string NewSitePageTitle {
            get {
                return ResourceManager.GetString("NewSitePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new site was created successfully..
        /// </summary>
        internal static string NewSiteSuccessPageTitle {
            get {
                return ResourceManager.GetString("NewSiteSuccessPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note that the url of the new site must be accesible. Verify that the physical directory of the url points to the Cuyahoga installation..
        /// </summary>
        internal static string NewSiteWarningText {
            get {
                return ResourceManager.GetString("NewSiteWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user.
        /// </summary>
        internal static string NewUserPageTitle {
            get {
                return ResourceManager.GetString("NewUserPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file was uploaded..
        /// </summary>
        internal static string NoFileUploadedMessage {
            get {
                return ResourceManager.GetString("NoFileUploadedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string NoneLabel {
            get {
                return ResourceManager.GetString("NoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No role(s) found.
        /// </summary>
        internal static string NoRolesFound {
            get {
                return ResourceManager.GetString("NoRolesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No templates found.
        /// </summary>
        internal static string NoTemplatesFound {
            get {
                return ResourceManager.GetString("NoTemplatesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user(s) found.
        /// </summary>
        internal static string NoUsersFound {
            get {
                return ResourceManager.GetString("NoUsersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OkLabel {
            get {
                return ResourceManager.GetString("OkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string OptionAll {
            get {
                return ResourceManager.GetString("OptionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page is copied successfully..
        /// </summary>
        internal static string PageCopiedMessage {
            get {
                return ResourceManager.GetString("PageCopiedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page {0} was created successfully. You can now choose a template and add content..
        /// </summary>
        internal static string PageCreatedMessage {
            get {
                return ResourceManager.GetString("PageCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page {0} was deleted successfully..
        /// </summary>
        internal static string PageDeletedMessage {
            get {
                return ResourceManager.GetString("PageDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string PageLabel {
            get {
                return ResourceManager.GetString("PageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page is moved successfully..
        /// </summary>
        internal static string PageMovedMessage {
            get {
                return ResourceManager.GetString("PageMovedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order of de pages is updated..
        /// </summary>
        internal static string PageOrderUpdatedMessage {
            get {
                return ResourceManager.GetString("PageOrderUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page properties.
        /// </summary>
        internal static string PagePropertiesLabel {
            get {
                return ResourceManager.GetString("PagePropertiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page properties are updated..
        /// </summary>
        internal static string PagePropertiesUpdatedMessage {
            get {
                return ResourceManager.GetString("PagePropertiesUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page title.
        /// </summary>
        internal static string PageTitleLabel {
            get {
                return ResourceManager.GetString("PageTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page url.
        /// </summary>
        internal static string PageUrlLabel {
            get {
                return ResourceManager.GetString("PageUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent category.
        /// </summary>
        internal static string ParentCategoryLabel {
            get {
                return ResourceManager.GetString("ParentCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is changed successfully..
        /// </summary>
        internal static string PasswordChangedMessage {
            get {
                return ResourceManager.GetString("PasswordChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string PathLabel {
            get {
                return ResourceManager.GetString("PathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions for {0} are updated successfully..
        /// </summary>
        internal static string PermissionsUpdatedMessage {
            get {
                return ResourceManager.GetString("PermissionsUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string PlaceholderLabel {
            get {
                return ResourceManager.GetString("PlaceholderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propagate permissions.
        /// </summary>
        internal static string PropagatePermissionsLabel {
            get {
                return ResourceManager.GetString("PropagatePermissionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propagate to child pages.
        /// </summary>
        internal static string PropagateToChildPagesLabel {
            get {
                return ResourceManager.GetString("PropagateToChildPagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propagate to sections on the page.
        /// </summary>
        internal static string PropagateToChildSectionsLabel {
            get {
                return ResourceManager.GetString("PropagateToChildSectionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild full-text index.
        /// </summary>
        internal static string RebuildFullTextIndexLabel {
            get {
                return ResourceManager.GetString("RebuildFullTextIndexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Text index.
        /// </summary>
        internal static string RebuildFullTextIndexPageTitle {
            get {
                return ResourceManager.GetString("RebuildFullTextIndexPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new template.
        /// </summary>
        internal static string RegisterTemplateLabel {
            get {
                return ResourceManager.GetString("RegisterTemplateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new template.
        /// </summary>
        internal static string RegisterTemplatePageTitle {
            get {
                return ResourceManager.GetString("RegisterTemplatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove or detach section from page.
        /// </summary>
        internal static string RemoveSectionDialogTitle {
            get {
                return ResourceManager.GetString("RemoveSectionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove section.
        /// </summary>
        internal static string RemoveSectionLabel {
            get {
                return ResourceManager.GetString("RemoveSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rights.
        /// </summary>
        internal static string RightsLabel {
            get {
                return ResourceManager.GetString("RightsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role {0} is created successfully..
        /// </summary>
        internal static string RoleCreatedMessage {
            get {
                return ResourceManager.GetString("RoleCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role {0} is deleted successfully..
        /// </summary>
        internal static string RoleDeletedMessage {
            get {
                return ResourceManager.GetString("RoleDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string RoleLabel {
            get {
                return ResourceManager.GetString("RoleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string RolesLabel {
            get {
                return ResourceManager.GetString("RolesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role {0} is updated successfully..
        /// </summary>
        internal static string RoleUpdatedMessage {
            get {
                return ResourceManager.GetString("RoleUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButtonLabel {
            get {
                return ResourceManager.GetString("SaveButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section is attached or detached to template(s) succesfully..
        /// </summary>
        internal static string SectionAttachedMessage {
            get {
                return ResourceManager.GetString("SectionAttachedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbound connections.
        /// </summary>
        internal static string SectionConnectionsLabel {
            get {
                return ResourceManager.GetString("SectionConnectionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The section {0} is created successfully..
        /// </summary>
        internal static string SectionCreatedMessage {
            get {
                return ResourceManager.GetString("SectionCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The section {0} is successfully deleted..
        /// </summary>
        internal static string SectionDeletedMessage {
            get {
                return ResourceManager.GetString("SectionDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The section {0} is successfully detached from this page..
        /// </summary>
        internal static string SectionDetachedMessage {
            get {
                return ResourceManager.GetString("SectionDetachedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string SectionLabel {
            get {
                return ResourceManager.GetString("SectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section name.
        /// </summary>
        internal static string SectionNameLabel {
            get {
                return ResourceManager.GetString("SectionNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section permissions.
        /// </summary>
        internal static string SectionPermissionsLabel {
            get {
                return ResourceManager.GetString("SectionPermissionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section properties.
        /// </summary>
        internal static string SectionPropertiesDialogTitle {
            get {
                return ResourceManager.GetString("SectionPropertiesDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section properties.
        /// </summary>
        internal static string SectionPropertiesLabel {
            get {
                return ResourceManager.GetString("SectionPropertiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section properties are saved successfully..
        /// </summary>
        internal static string SectionPropertiesUpdatedMessage {
            get {
                return ResourceManager.GetString("SectionPropertiesUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections arranged for placeholder {0}..
        /// </summary>
        internal static string SectionsArrangedMessage {
            get {
                return ResourceManager.GetString("SectionsArrangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select action.
        /// </summary>
        internal static string SelectActionOption {
            get {
                return ResourceManager.GetString("SelectActionOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected section.
        /// </summary>
        internal static string SelectedSectionLabel {
            get {
                return ResourceManager.GetString("SelectedSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SelectLabel {
            get {
                return ResourceManager.GetString("SelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select module type.
        /// </summary>
        internal static string SelectModuleTypeLabel {
            get {
                return ResourceManager.GetString("SelectModuleTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in navigation.
        /// </summary>
        internal static string ShowInNavigationLabel {
            get {
                return ResourceManager.GetString("ShowInNavigationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string SiteLabel {
            get {
                return ResourceManager.GetString("SiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site is updated successfully..
        /// </summary>
        internal static string SiteUpdatedMessage {
            get {
                return ResourceManager.GetString("SiteUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site url.
        /// </summary>
        internal static string SiteUrlLabel {
            get {
                return ResourceManager.GetString("SiteUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string SizeLabel {
            get {
                return ResourceManager.GetString("SizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string TasksLabel {
            get {
                return ResourceManager.GetString("TasksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template control.
        /// </summary>
        internal static string TemplateControlLabel {
            get {
                return ResourceManager.GetString("TemplateControlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template {0} is created successfully..
        /// </summary>
        internal static string TemplateCreatedMessage {
            get {
                return ResourceManager.GetString("TemplateCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template {0} is deleted successfully..
        /// </summary>
        internal static string TemplateDeletedMessage {
            get {
                return ResourceManager.GetString("TemplateDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string TemplateLabel {
            get {
                return ResourceManager.GetString("TemplateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template was successfully connected to the page..
        /// </summary>
        internal static string TemplateSetMessage {
            get {
                return ResourceManager.GetString("TemplateSetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string TemplatesLabel {
            get {
                return ResourceManager.GetString("TemplatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template files are uploaded. You can now register one or more new templates based on the files..
        /// </summary>
        internal static string TemplatesUploadedMessage {
            get {
                return ResourceManager.GetString("TemplatesUploadedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template {0} is updated successfully..
        /// </summary>
        internal static string TemplateUpdatedMessage {
            get {
                return ResourceManager.GetString("TemplateUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time zone.
        /// </summary>
        internal static string TimeZoneLabel {
            get {
                return ResourceManager.GetString("TimeZoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not installed.
        /// </summary>
        internal static string UninstalledStatus {
            get {
                return ResourceManager.GetString("UninstalledStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        internal static string UninstallLabel {
            get {
                return ResourceManager.GetString("UninstallLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module cannot be uninstalled because it is used in the following sections.
        /// </summary>
        internal static string UninstallModuleForbiddenBecauseOfRelatedSectionsMessage {
            get {
                return ResourceManager.GetString("UninstallModuleForbiddenBecauseOfRelatedSectionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade.
        /// </summary>
        internal static string UpgradeLabel {
            get {
                return ResourceManager.GetString("UpgradeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string UploadButtonLabel {
            get {
                return ResourceManager.GetString("UploadButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload files.
        /// </summary>
        internal static string UploadFilesLabel {
            get {
                return ResourceManager.GetString("UploadFilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can upload a set of template files, packaged as a .zip file. The name of the .zip file becomes the directory name. Make sure that the template control (.ascx) is in the root of the package and images and stylesheets are in the &apos;Images&apos; and &apos;Css&apos; directories..
        /// </summary>
        internal static string UploadNewTemplateFilesHint {
            get {
                return ResourceManager.GetString("UploadNewTemplateFilesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload new template files.
        /// </summary>
        internal static string UploadNewTemplateFilesLabel {
            get {
                return ResourceManager.GetString("UploadNewTemplateFilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use friendly urls.
        /// </summary>
        internal static string UseFriendlyUrlsLabel {
            get {
                return ResourceManager.GetString("UseFriendlyUrlsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user {0} is created successfully..
        /// </summary>
        internal static string UserCreatedMessage {
            get {
                return ResourceManager.GetString("UserCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user {0} is deleted successfully..
        /// </summary>
        internal static string UserDeletedMessage {
            get {
                return ResourceManager.GetString("UserDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current user is not a valid authenticated Cuyahoga user.
        /// </summary>
        internal static string UserNullException {
            get {
                return ResourceManager.GetString("UserNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string UsersLabel {
            get {
                return ResourceManager.GetString("UsersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user {0} is updated successfully..
        /// </summary>
        internal static string UserUpdatedMessage {
            get {
                return ResourceManager.GetString("UserUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ViewLabel {
            get {
                return ResourceManager.GetString("ViewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles that are allowed to view the content.
        /// </summary>
        internal static string ViewRolesLabel {
            get {
                return ResourceManager.GetString("ViewRolesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View template.
        /// </summary>
        internal static string ViewTemplatePageTitle {
            get {
                return ResourceManager.GetString("ViewTemplatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webmaster email.
        /// </summary>
        internal static string WebmasterEmailLabel {
            get {
                return ResourceManager.GetString("WebmasterEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web site.
        /// </summary>
        internal static string WebsiteLabel {
            get {
                return ResourceManager.GetString("WebsiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With the selected items do.
        /// </summary>
        internal static string WithSelectedItemsDo {
            get {
                return ResourceManager.GetString("WithSelectedItemsDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
