//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Cuyahoga.Web.Controls.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Cuyahoga.Web.Controls.Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string CURRENTPASSWORD {
            get {
                return ResourceManager.GetString("CURRENTPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was successfully updated..
        /// </summary>
        internal static string EDITPASSWORDCONFIRMATION {
            get {
                return ResourceManager.GetString("EDITPASSWORDCONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation password has to be the same as the new password..
        /// </summary>
        internal static string EDITPASSWORDCONFIRMERROR {
            get {
                return ResourceManager.GetString("EDITPASSWORDCONFIRMERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password you entered doesn&apos;t match your real current password..
        /// </summary>
        internal static string EDITPASSWORDCURRENTERROR {
            get {
                return ResourceManager.GetString("EDITPASSWORDCURRENTERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account information was successfully updated..
        /// </summary>
        internal static string EDITPROFILECONFIRMATION {
            get {
                return ResourceManager.GetString("EDITPROFILECONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your account information. Note that your e-mail address will never be publicly shown..
        /// </summary>
        internal static string EDITPROFILEINFO {
            get {
                return ResourceManager.GetString("EDITPROFILEINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update account.
        /// </summary>
        internal static string EDITPROFILETITLE {
            get {
                return ResourceManager.GetString("EDITPROFILETITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid e-mail address.
        /// </summary>
        internal static string EMAILINVALID {
            get {
                return ResourceManager.GetString("EMAILINVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail address is required.
        /// </summary>
        internal static string EMAILREQUIRED {
            get {
                return ResourceManager.GetString("EMAILREQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FIRSTNAME {
            get {
                return ResourceManager.GetString("FIRSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered an invalid password. The password has to be at least 5 characters long..
        /// </summary>
        internal static string INVALIDPASSWORD {
            get {
                return ResourceManager.GetString("INVALIDPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last visit.
        /// </summary>
        internal static string LASTLOGINON {
            get {
                return ResourceManager.GetString("LASTLOGINON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LASTNAME {
            get {
                return ResourceManager.GetString("LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string NEWPASSWORD {
            get {
                return ResourceManager.GetString("NEWPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password (confirmation).
        /// </summary>
        internal static string NEWPASSWORDCONFIRMATION {
            get {
                return ResourceManager.GetString("NEWPASSWORDCONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to be logged in perform this action..
        /// </summary>
        internal static string NOTAUTHENTICATED {
            get {
                return ResourceManager.GetString("NOTAUTHENTICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string REGISTER {
            get {
                return ResourceManager.GetString("REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for registering with this site. An e-mail with the password is sent to {0}..
        /// </summary>
        internal static string REGISTERCONFIRMATION {
            get {
                return ResourceManager.GetString("REGISTERCONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered.
        /// </summary>
        internal static string REGISTEREDON {
            get {
                return ResourceManager.GetString("REGISTEREDON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your registration at {site}.
        ///
        ///Username: {username}
        ///Password: {password}
        ///
        ///Have fun!.
        /// </summary>
        internal static string REGISTEREMAILBODY {
            get {
                return ResourceManager.GetString("REGISTEREMAILBODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registration failed because an error occured while sending your account information. Please try again later..
        /// </summary>
        internal static string REGISTEREMAILERROR {
            get {
                return ResourceManager.GetString("REGISTEREMAILERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {site} account information.
        /// </summary>
        internal static string REGISTEREMAILSUBJECT {
            get {
                return ResourceManager.GetString("REGISTEREMAILSUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the desired username and your e-mail address. The password will be sent to your e-mail address..
        /// </summary>
        internal static string REGISTERINFO {
            get {
                return ResourceManager.GetString("REGISTERINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as new user.
        /// </summary>
        internal static string REGISTERTITLE {
            get {
                return ResourceManager.GetString("REGISTERTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        internal static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An e-mail with a new password is sent to {0}..
        /// </summary>
        internal static string RESETCONFIRMATION {
            get {
                return ResourceManager.GetString("RESETCONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your updated login information:
        ///
        ///Username: {username}
        ///Password: {password}.
        /// </summary>
        internal static string RESETEMAILBODY {
            get {
                return ResourceManager.GetString("RESETEMAILBODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting of your password failed because an error occured while sending your account information. Please try to reset again later..
        /// </summary>
        internal static string RESETEMAILERROR {
            get {
                return ResourceManager.GetString("RESETEMAILERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {site} updated account information..
        /// </summary>
        internal static string RESETEMAILSUBJECT {
            get {
                return ResourceManager.GetString("RESETEMAILSUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username and e-mail address. A new password will be generated and send to you..
        /// </summary>
        internal static string RESETINFO {
            get {
                return ResourceManager.GetString("RESETINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        internal static string RESETTITLE {
            get {
                return ResourceManager.GetString("RESETTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user was found with the given username and e-mail..
        /// </summary>
        internal static string RESETUSERERROR {
            get {
                return ResourceManager.GetString("RESETUSERERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save new password.
        /// </summary>
        internal static string SAVEPASSWORD {
            get {
                return ResourceManager.GetString("SAVEPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save account information.
        /// </summary>
        internal static string SAVEPROFILE {
            get {
                return ResourceManager.GetString("SAVEPROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        internal static string TIMEZONE {
            get {
                return ResourceManager.GetString("TIMEZONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with username {0} already exists. Please choose a different username..
        /// </summary>
        internal static string USEREXISTS {
            get {
                return ResourceManager.GetString("USEREXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username is required.
        /// </summary>
        internal static string USERNAMEREQUIRED {
            get {
                return ResourceManager.GetString("USERNAMEREQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user with ID {0} could not be found..
        /// </summary>
        internal static string USERNOTFOUND {
            get {
                return ResourceManager.GetString("USERNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile of {0}.
        /// </summary>
        internal static string VIEWPROFILETITLE {
            get {
                return ResourceManager.GetString("VIEWPROFILETITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string WEBSITE {
            get {
                return ResourceManager.GetString("WEBSITE", resourceCulture);
            }
        }
    }
}
