//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Cuyahoga.Modules.Downloads {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Cuyahoga.Modules.Downloads.GlobalResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/upload new file.
        /// </summary>
        internal static string AddNewFileButtonLabel {
            get {
                return ResourceManager.GetString("AddNewFileButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteButtonLabel {
            get {
                return ResourceManager.GetString("DeleteButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        internal static string DownloadsLabel {
            get {
                return ResourceManager.GetString("DownloadsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit file.
        /// </summary>
        internal static string EditFilePageTitle {
            get {
                return ResourceManager.GetString("EditFilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditLabel {
            get {
                return ResourceManager.GetString("EditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is deleted successfully..
        /// </summary>
        internal static string FileDeletedMessage {
            get {
                return ResourceManager.GetString("FileDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is required.
        /// </summary>
        internal static string FileIsRequired {
            get {
                return ResourceManager.GetString("FileIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileLabel {
            get {
                return ResourceManager.GetString("FileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string FileNameLabel {
            get {
                return ResourceManager.GetString("FileNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File properties.
        /// </summary>
        internal static string FilePropertiesLabel {
            get {
                return ResourceManager.GetString("FilePropertiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is saved successfully..
        /// </summary>
        internal static string FileSavedMessage {
            get {
                return ResourceManager.GetString("FileSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage files.
        /// </summary>
        internal static string ManageFilesPageTitle {
            get {
                return ResourceManager.GetString("ManageFilesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/upload a new file.
        /// </summary>
        internal static string NewFilePageTitle {
            get {
                return ResourceManager.GetString("NewFilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file was uploaded..
        /// </summary>
        internal static string NoFileUploadedMessage {
            get {
                return ResourceManager.GetString("NoFileUploadedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string PermissionsLabel {
            get {
                return ResourceManager.GetString("PermissionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish date is required.
        /// </summary>
        internal static string PublishedAtIsRequired {
            get {
                return ResourceManager.GetString("PublishedAtIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish date.
        /// </summary>
        internal static string PublishedLabel {
            get {
                return ResourceManager.GetString("PublishedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish until.
        /// </summary>
        internal static string PublishedUntilLabel {
            get {
                return ResourceManager.GetString("PublishedUntilLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string PublisherLabel {
            get {
                return ResourceManager.GetString("PublisherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing.
        /// </summary>
        internal static string PublishingLabel {
            get {
                return ResourceManager.GetString("PublishingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download/view allowed for.
        /// </summary>
        internal static string RolesViewAllowedLabel {
            get {
                return ResourceManager.GetString("RolesViewAllowedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save/upload file.
        /// </summary>
        internal static string SaveButtonLabel {
            get {
                return ResourceManager.GetString("SaveButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string SizeLabel {
            get {
                return ResourceManager.GetString("SizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string SummaryLabel {
            get {
                return ResourceManager.GetString("SummaryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syndicate.
        /// </summary>
        internal static string SyndicateLabel {
            get {
                return ResourceManager.GetString("SyndicateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
    }
}
