/*                                                          */
/* File generated by "DeZign for databases"                 */
/* Create-date    :10/21/2004                               */
/* Create-time    :10:52:13 PM                              */
/* project-name   :Cuyahoga                                 */
/* project-author :Martijn Boland                           */
/*                                                          */



CREATE TABLE Cuyahoga_Culture(
Culture varchar(8) NOT NULL PRIMARY KEY,
NeutralCulture varchar(2) NOT NULL,
Description varchar(50) NOT NULL);

