/*                                                          */
/* File generated by "DeZign for databases"                 */
/* Create-date    :10/2/2004                                */
/* Create-time    :3:01:29 PM                               */
/* project-name   :Cuyahoga                                 */
/* project-author :Martijn Boland                           */
/*                                                          */



CREATE TABLE Cuyahoga_ModuleType(
ModuleTypeId serial NOT NULL PRIMARY KEY,
Name varchar(100) NOT NULL,
AssemblyName varchar(100),
ClassName varchar(255) NOT NULL UNIQUE,
Path varchar(255) NOT NULL,
EditPath varchar(255),
InsertTimestamp timestamp DEFAULT current_timestamp NOT NULL,
UpdateTimestamp timestamp DEFAULT current_timestamp NOT NULL);

