/*                                                          */
/* File generated by "DeZign for databases"                 */
/* Create-date    :10/7/2004                                */
/* Create-time    :10:41:23 PM                              */
/* project-name   :Cuyahoga                                 */
/* project-author :Martijn Boland                           */
/*                                                          */



CREATE TABLE Cuyahoga_Permission(
PermissionId serial NOT NULL PRIMARY KEY,
RoleId int4 NOT NULL,
ObjectId int4 NOT NULL,
ObjectType varchar(50) NOT NULL,
ViewAllowed bool NOT NULL,
EditAllowed bool NOT NULL,
InsertTimeStamp timestamp DEFAULT current_timestamp(3) NOT NULL,
UpdateTimestamp timestamp DEFAULT current_timestamp(3) NOT NULL,
FOREIGN KEY (RoleId) REFERENCES Cuyahoga_Role (RoleId));

CREATE UNIQUE INDEX IDX_Cuyahoga_Permission_1 ON Cuyahoga_Permission (RoleId,ObjectType,ObjectId);
CREATE INDEX IDX_Cuyahoga_Permission_2 ON Cuyahoga_Permission (ObjectId,ObjectType);
