using System;
using System.Collections;

using Gentle.Framework;

using Cuyahoga.Core;
using Cuyahoga.Core.DAL;

namespace Cuyahoga.Modules.Articles
{
	/// <summary>
	/// Summary description for Article.
	/// </summary>
	[TableName("cm_article")]
	public class Article : Persistent
	{
		[TableColumn("articleid"), PrimaryKey(AutoGenerated=true), SequenceName("cm_article_articleid_seq")] 
		private int _id;
		[TableColumn("sectionid")]
		private int _sectionId;
		[TableColumn("createdby")]
		private int _createdById;
		[TableColumn("modifiedby")]
		private int _modifiedById;
		[TableColumn("articlecategoryid")]
		private int _categoryId;
		private string _title;
		private string _summary;
		private string _content;
		private bool _syndicate;
		private DateTime _dateOnline;
		private DateTime _dateOffline;
		private DateTime _dateCreated;
		private DateTime _dateModified;
		private Section _section;
		private Cuyahoga.Core.User _createdBy;
		private Cuyahoga.Core.User _modifiedBy;
		private Category _category;
		private GentleList _comments;

		#region properties

		/// <summary>
		/// Property Id (int)
		/// </summary>
		public int Id
		{
			get { return this._id; }
		}

		/// <summary>
		/// Property Title (string)
		/// </summary>
		[TableColumn("title")]
		public string Title
		{
			get { return this._title; }
			set { this._title = value; }
		}

		/// <summary>
		/// Property Summary (string)
		/// </summary>
		[TableColumn("summary", NotNull=true)]
		public string Summary
		{
			get { return this._summary; }
			set { this._summary = value; }
		}

		/// <summary>
		/// Property Content (string)
		/// </summary>
		[TableColumn("content")]
		public string Content
		{
			get { return this._content; }
			set { this._content = value; }
		}

		/// <summary>
		/// Property DateOnline (DateTime)
		/// </summary>
		[TableColumn("dateonline")]
		public DateTime DateOnline
		{
			get { return this._dateOnline; }
			set { this._dateOnline = value; }
		}

		/// <summary>
		/// Property DateOffline (DateTime)
		/// </summary>
		[TableColumn("dateoffline")]
		public DateTime DateOffline
		{
			get { return this._dateOffline; }
			set { this._dateOffline = value; }
		}

		/// <summary>
		/// Property DateCreated (DateTime)
		/// </summary>
		[TableColumn("inserttimestamp")]
		public DateTime DateCreated
		{
			get { return this._dateCreated; }
			set { this._dateCreated = value; }
		}

		/// <summary>
		/// Property DateModified (DateTime)
		/// </summary>
		[TableColumn("updatetimestamp")]
		public DateTime DateModified
		{
			get { return this._dateModified; }
			set { this._dateModified = value; }
		}
		/// <summary>
		/// Property Syndicate (bool)
		/// </summary>
		[TableColumn("syndicate")]
		public bool Syndicate
		{
			get { return this._syndicate; }
			set { this._syndicate = value; }
		}

		/// <summary>
		/// Property Section (Section)
		/// </summary>
		public Section Section
		{
			get 
			{ 
				if (this._section == null && this._sectionId > 0)
				{
					this._section = new Section(this._sectionId);
				}
				return this._section; 
			}
			set 
			{ 
				this._section = value; 
				this._sectionId = this._section.Id;
			}
		}

		/// <summary>
		/// Property CreatedBy (User)
		/// </summary>
		public Cuyahoga.Core.User CreatedBy
		{
			get 
			{ 
				if (this._createdBy == null && this._createdById > 0)
				{
					this._createdBy = new Cuyahoga.Core.User(this._createdById);
				}
				return this._createdBy; 
			}
			set 
			{ 
				this._createdBy = value; 
				this._createdById = this._createdBy.Id;
			}
		}

		/// <summary>
		/// Property ModifiedBy (User)
		/// </summary>
		public Cuyahoga.Core.User ModifiedBy
		{
			get 
			{ 
				if (this._modifiedBy == null && this._modifiedById > 0)
				{
					this._modifiedBy = new Cuyahoga.Core.User(this._modifiedById);
				}
				return this._modifiedBy; 
			}
			set 
			{ 
				this._modifiedBy = value; 
				this._modifiedById = this._modifiedBy.Id;
			}
		}

		/// <summary>
		/// Property Category (Category)
		/// </summary>
		public Category Category
		{
			get 
			{ 
				if (this._category == null && this._categoryId > 0)
				{
					Key key = new Key(typeof(Category), true, "Id", this._categoryId);
					this._category = Category.Retrieve(typeof(Category), key) as Category;
				}
				return this._category; 
			}
			set 
			{ 
				this._category = value; 
				this._categoryId = this._category.Id;
			}
		}

		/// <summary>
		/// Property Comments (IList)
		/// </summary>
		public IList Comments
		{
			get 
			{ 
				if (this._comments == null)
				{
					this._comments = new GentleList(typeof(Comment), this);
				}
				return this._comments; 
			}
		}

		#endregion

		/// <summary>
		/// Default constructor.
		/// </summary>
		public Article()
		{
			this._id = -1;
			this._sectionId = -1;
			this._createdById = -1;
			this._modifiedById = -1;
			this._categoryId = -1;
			this._syndicate = true;
			this._dateOnline = DateTime.MinValue;
			this._dateOffline = DateTime.MinValue;
			this._dateCreated = DateTime.MinValue;
			this._dateModified = DateTime.MinValue;
		}
	}
}
