using System;
using System.Collections;

using Gentle.Framework;

using Cuyahoga.Core;
using Cuyahoga.Core.DAL;

namespace Cuyahoga.Modules.Articles
{
	/// <summary>
	/// Summary description for Article.
	/// </summary>
	[TableName("cm_article")]
	public class Article : Persistent
	{
		[TableColumn("articleid"), PrimaryKey(AutoGenerated=true), SequenceName("cm_article_articleid_seq")] 
		private int _id;
		[TableColumn("sectionid")]
		private int _sectionId;
		[TableColumn("createdby")]
		private int _createdById;
		[TableColumn("modifiedby", NotNull=true, MagicValue=0)]
		private int _modifiedById;
		[TableColumn("articlecategoryid", NotNull=true, MagicValue=0), ForeignKey("articlecategory", "articlecategoryid")]
		private int _categoryId;
		private string _title;
		private string _summary;
		private string _content;
		private bool _syndicate;
		private DateTime _dateOnline;
		private DateTime _dateOffline;
		private DateTime _dateCreated;
		private DateTime _dateModified;
		private Section _section;
		private Cuyahoga.Core.User _createdBy;
		private Cuyahoga.Core.User _modifiedBy;
		private Category _category;
		private GentleList _comments;

		#region properties

		/// <summary>
		/// Property Id (int)
		/// </summary>
		public int Id
		{
			get { return this._id; }
		}

		/// <summary>
		/// Property Title (string)
		/// </summary>
		[TableColumn("title")]
		public string Title
		{
			get { return this._title; }
			set { this._title = value; }
		}

		/// <summary>
		/// Property Summary (string)
		/// </summary>
		[TableColumn("summary", NotNull=true)]
		public string Summary
		{
			get { return this._summary; }
			set { this._summary = value; }
		}

		/// <summary>
		/// Property Content (string)
		/// </summary>
		[TableColumn("content")]
		public string Content
		{
			get { return this._content; }
			set { this._content = value; }
		}

		/// <summary>
		/// Property DateOnline (DateTime)
		/// </summary>
		[TableColumn("dateonline")]
		public DateTime DateOnline
		{
			get { return this._dateOnline; }
			set { this._dateOnline = value; }
		}

		/// <summary>
		/// Property DateOffline (DateTime)
		/// </summary>
		[TableColumn("dateoffline")]
		public DateTime DateOffline
		{
			get { return this._dateOffline; }
			set { this._dateOffline = value; }
		}

		/// <summary>
		/// Property DateCreated (DateTime)
		/// </summary>
		[TableColumn("inserttimestamp")]
		public DateTime DateCreated
		{
			get { return this._dateCreated; }
			set { this._dateCreated = value; }
		}

		/// <summary>
		/// Property DateModified (DateTime)
		/// </summary>
		[TableColumn("updatetimestamp")]
		public DateTime DateModified
		{
			get { return this._dateModified; }
			set { this._dateModified = value; }
		}
		/// <summary>
		/// Property Syndicate (bool)
		/// </summary>
		[TableColumn("syndicate")]
		public bool Syndicate
		{
			get { return this._syndicate; }
			set { this._syndicate = value; }
		}

		/// <summary>
		/// Property Section (Section)
		/// </summary>
		public Section Section
		{
			get 
			{ 
				if (this._section == null && this._sectionId > 0)
				{
					this._section = new Section(this._sectionId);
				}
				return this._section; 
			}
			set 
			{ 
				this._section = value;
				if (value != null)
				{
					this._sectionId = this._section.Id;
				}
			}
		}

		/// <summary>
		/// Property CreatedBy (User)
		/// </summary>
		public Cuyahoga.Core.User CreatedBy
		{
			get 
			{ 
				if (this._createdBy == null && this._createdById > 0)
				{
					this._createdBy = new Cuyahoga.Core.User(this._createdById);
				}
				return this._createdBy; 
			}
			set 
			{ 
				this._createdBy = value; 
				if (value != null)
				{
					this._createdById = this._createdBy.Id;
				}
			}
		}

		/// <summary>
		/// Property ModifiedBy (User)
		/// </summary>
		public Cuyahoga.Core.User ModifiedBy
		{
			get 
			{ 
				if (this._modifiedBy == null && this._modifiedById > 0)
				{
					this._modifiedBy = new Cuyahoga.Core.User(this._modifiedById);
				}
				return this._modifiedBy; 
			}
			set 
			{ 
				this._modifiedBy = value; 
				if (value != null)
				{
					this._modifiedById = this._modifiedBy.Id;
				}
				else
				{
					this._modifiedById = 0;
				}
			}
		}

		/// <summary>
		/// Property Category (Category)
		/// </summary>
		public Category Category
		{
			get 
			{ 
				if (this._category == null && this._categoryId > 0)
				{
					this._category = new Category(this._categoryId);
				}
				return this._category; 
			}
			set 
			{ 
				this._category = value; 
				if (value != null)
				{
					this._categoryId = this._category.Id;
				}
				else
				{
					this._categoryId = 0;
				}
			}
		}

		/// <summary>
		/// Property Comments (IList)
		/// </summary>
		public IList Comments
		{
			get 
			{ 
				if (this._comments == null)
				{
					this._comments = new GentleList(typeof(Comment), this);
				}
				return this._comments; 
			}
		}

		#endregion

		#region constructors

		/// <summary>
		/// Default constructor.
		/// </summary>
		public Article()
		{
			this._id = 0;
			this._sectionId = 0;
			this._createdById = 0;
			this._modifiedById = 0;
			this._categoryId = 0;
			this._syndicate = true;
			this._dateOnline = DateTime.MinValue;
			this._dateOffline = DateTime.MinValue;
			this._dateCreated = DateTime.Now;
			this._dateModified = DateTime.Now;
		}

		/// <summary>
		/// Constructor with all persistant fields.
		/// </summary>
		/// <param name="id"></param>
		/// <param name="sectionId"></param>
		/// <param name="createdById"></param>
		/// <param name="modifiedById"></param>
		/// <param name="categoryId"></param>
		/// <param name="title"></param>
		/// <param name="summary"></param>
		/// <param name="content"></param>
		/// <param name="syndicate"></param>
		/// <param name="dateOnline"></param>
		/// <param name="dateOffline"></param>
		/// <param name="dateCreated"></param>
		/// <param name="dateModified"></param>
		public Article(int id, int sectionId, int createdById, int modifiedById, int categoryId, string title, string summary, string content
			, bool syndicate, DateTime dateOnline, DateTime dateOffline, DateTime dateCreated, DateTime dateModified)
		{
			this._id = id;
			this._sectionId = sectionId;
			this._createdById = createdById;
			this._modifiedById = modifiedById;
			this._categoryId = categoryId;
			this._title = title;
			this._summary = summary;
			this._content = content;
			this._syndicate = syndicate;
			this._dateOnline = dateOnline;
			this._dateOffline = dateOffline;
			this._dateCreated = dateCreated;
			this._dateModified = dateModified;
		}

		/// <summary>
		/// Constructor to create a populated Article.
		/// </summary>
		/// <param name="id"></param>
		public Article(int id)
		{
			if (id > 0)
			{
				this._id = id;
				Broker.Refresh(this);
			}
		}

		#endregion
	}
}
