//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Cuyahoga.Web.Manager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Cuyahoga.Web.Manager.GlobalResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to perform the requested action..
        /// </summary>
        internal static string ActionNotAllowedException {
            get {
                return ResourceManager.GetString("ActionNotAllowedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while authenticating the user..
        /// </summary>
        internal static string AuthenticationException {
            get {
                return ResourceManager.GetString("AuthenticationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ChangePasswordLabel {
            get {
                return ResourceManager.GetString("ChangePasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string ConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy templates.
        /// </summary>
        internal static string CopyTemplatesLabel {
            get {
                return ResourceManager.GetString("CopyTemplatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new role.
        /// </summary>
        internal static string CreateRoleLabel {
            get {
                return ResourceManager.GetString("CreateRoleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new site.
        /// </summary>
        internal static string CreateSiteLabel {
            get {
                return ResourceManager.GetString("CreateSiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create user.
        /// </summary>
        internal static string CreateUserLabel {
            get {
                return ResourceManager.GetString("CreateUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuyahoga Site Manager.
        /// </summary>
        internal static string CuyahogaSiteManagerLabel {
            get {
                return ResourceManager.GetString("CuyahogaSiteManagerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string DashboardPageTitle {
            get {
                return ResourceManager.GetString("DashboardPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default culture.
        /// </summary>
        internal static string DefaultCultureLabel {
            get {
                return ResourceManager.GetString("DefaultCultureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default role for authenticated users.
        /// </summary>
        internal static string DefaultRoleLabel {
            get {
                return ResourceManager.GetString("DefaultRoleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults.
        /// </summary>
        internal static string DefaultsLabel {
            get {
                return ResourceManager.GetString("DefaultsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteButtonLabel {
            get {
                return ResourceManager.GetString("DeleteButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete yourself..
        /// </summary>
        internal static string DeleteYourselfNotAllowedException {
            get {
                return ResourceManager.GetString("DeleteYourselfNotAllowedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditLabel {
            get {
                return ResourceManager.GetString("EditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit role.
        /// </summary>
        internal static string EditRolePageTitle {
            get {
                return ResourceManager.GetString("EditRolePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        internal static string EditUserPageTitle {
            get {
                return ResourceManager.GetString("EditUserPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password may not be empty..
        /// </summary>
        internal static string EmptyUsernameOrPassword {
            get {
                return ResourceManager.GetString("EmptyUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string FilterButtonLabel {
            get {
                return ResourceManager.GetString("FilterButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string GeneralLabel {
            get {
                return ResourceManager.GetString("GeneralLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in all sites.
        /// </summary>
        internal static string GlobalSearchLabel {
            get {
                return ResourceManager.GetString("GlobalSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password. Make sure it has at least 5 characters..
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username-password combination..
        /// </summary>
        internal static string InvalidUsernamePassword {
            get {
                return ResourceManager.GetString("InvalidUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string IsActiveLabel {
            get {
                return ResourceManager.GetString("IsActiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is global.
        /// </summary>
        internal static string IsGlobalLabel {
            get {
                return ResourceManager.GetString("IsGlobalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last login from.
        /// </summary>
        internal static string LastLoginfromLabel {
            get {
                return ResourceManager.GetString("LastLoginfromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last login.
        /// </summary>
        internal static string LastLoginLabel {
            get {
                return ResourceManager.GetString("LastLoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as.
        /// </summary>
        internal static string LoggedInAsLabel {
            get {
                return ResourceManager.GetString("LoggedInAsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginButtonLabel {
            get {
                return ResourceManager.GetString("LoginButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LogoutButtonLabel {
            get {
                return ResourceManager.GetString("LogoutButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage files.
        /// </summary>
        internal static string ManageFilesPageTitle {
            get {
                return ResourceManager.GetString("ManageFilesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage pages and sections.
        /// </summary>
        internal static string ManagePagesPageTitle {
            get {
                return ResourceManager.GetString("ManagePagesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string ManagerMenuDashboard {
            get {
                return ResourceManager.GetString("ManagerMenuDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string ManagerMenuFiles {
            get {
                return ResourceManager.GetString("ManagerMenuFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        internal static string ManagerMenuPages {
            get {
                return ResourceManager.GetString("ManagerMenuPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage roles.
        /// </summary>
        internal static string ManagerMenuRoles {
            get {
                return ResourceManager.GetString("ManagerMenuRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server settings.
        /// </summary>
        internal static string ManagerMenuServer {
            get {
                return ResourceManager.GetString("ManagerMenuServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site settings.
        /// </summary>
        internal static string ManagerMenuSite {
            get {
                return ResourceManager.GetString("ManagerMenuSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string ManagerMenuTemplates {
            get {
                return ResourceManager.GetString("ManagerMenuTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users and roles.
        /// </summary>
        internal static string ManagerMenuUsers {
            get {
                return ResourceManager.GetString("ManagerMenuUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage roles.
        /// </summary>
        internal static string ManageRolesPageTitle {
            get {
                return ResourceManager.GetString("ManageRolesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage site.
        /// </summary>
        internal static string ManageSitePageTitle {
            get {
                return ResourceManager.GetString("ManageSitePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage templates.
        /// </summary>
        internal static string ManageTemplatesPageTitle {
            get {
                return ResourceManager.GetString("ManageTemplatesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        internal static string ManageUsersPageTitle {
            get {
                return ResourceManager.GetString("ManageUsersPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some errors have occured:.
        /// </summary>
        internal static string ModelValidationErrorMessage {
            get {
                return ResourceManager.GetString("ModelValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new role.
        /// </summary>
        internal static string NewRolePageTitle {
            get {
                return ResourceManager.GetString("NewRolePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new site.
        /// </summary>
        internal static string NewSitePageTitle {
            get {
                return ResourceManager.GetString("NewSitePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user.
        /// </summary>
        internal static string NewUserPageTitle {
            get {
                return ResourceManager.GetString("NewUserPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No role(s) found.
        /// </summary>
        internal static string NoRolesFound {
            get {
                return ResourceManager.GetString("NoRolesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user(s) found.
        /// </summary>
        internal static string NoUsersFound {
            get {
                return ResourceManager.GetString("NoUsersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string OptionAll {
            get {
                return ResourceManager.GetString("OptionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is changed successfully..
        /// </summary>
        internal static string PasswordChangedMessage {
            get {
                return ResourceManager.GetString("PasswordChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rights.
        /// </summary>
        internal static string RightsLabel {
            get {
                return ResourceManager.GetString("RightsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role {0} is created successfully..
        /// </summary>
        internal static string RoleCreatedMessage {
            get {
                return ResourceManager.GetString("RoleCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role {0} is deleted successfully..
        /// </summary>
        internal static string RoleDeletedMessage {
            get {
                return ResourceManager.GetString("RoleDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string RoleLabel {
            get {
                return ResourceManager.GetString("RoleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string RolesLabel {
            get {
                return ResourceManager.GetString("RolesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role {0} is updated successfully..
        /// </summary>
        internal static string RoleUpdatedMessage {
            get {
                return ResourceManager.GetString("RoleUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButtonLabel {
            get {
                return ResourceManager.GetString("SaveButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string SiteLabel {
            get {
                return ResourceManager.GetString("SiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site url.
        /// </summary>
        internal static string SiteUrlLabel {
            get {
                return ResourceManager.GetString("SiteUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string TasksLabel {
            get {
                return ResourceManager.GetString("TasksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string TemplatesLabel {
            get {
                return ResourceManager.GetString("TemplatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time zone.
        /// </summary>
        internal static string TimeZoneLabel {
            get {
                return ResourceManager.GetString("TimeZoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use friendly urls.
        /// </summary>
        internal static string UseFriendlyUrlsLabel {
            get {
                return ResourceManager.GetString("UseFriendlyUrlsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user {0} is created successfully..
        /// </summary>
        internal static string UserCreatedMessage {
            get {
                return ResourceManager.GetString("UserCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user {0} is deleted successfully..
        /// </summary>
        internal static string UserDeletedMessage {
            get {
                return ResourceManager.GetString("UserDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current user is not a valid authenticated Cuyahoga user.
        /// </summary>
        internal static string UserNullException {
            get {
                return ResourceManager.GetString("UserNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string UsersLabel {
            get {
                return ResourceManager.GetString("UsersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user {0} is updated successfully..
        /// </summary>
        internal static string UserUpdatedMessage {
            get {
                return ResourceManager.GetString("UserUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webmaster email.
        /// </summary>
        internal static string WebmasterEmailLabel {
            get {
                return ResourceManager.GetString("WebmasterEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web site.
        /// </summary>
        internal static string WebsiteLabel {
            get {
                return ResourceManager.GetString("WebsiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
