//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Cuyahoga.Web.Manager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "8.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Cuyahoga.Web.Manager.ValidationMessages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid e-mail address.
        /// </summary>
        internal static string EmailValidatorEmail {
            get {
                return ResourceManager.GetString("EmailValidatorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address must be between 1 and 100 characters.
        /// </summary>
        internal static string EmailValidatorLength {
            get {
                return ResourceManager.GetString("EmailValidatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address may not be empty.
        /// </summary>
        internal static string EmailValidatorNonEmpty {
            get {
                return ResourceManager.GetString("EmailValidatorNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firstname must be between 1 and 100 characters.
        /// </summary>
        internal static string FirstNameValidatorLength {
            get {
                return ResourceManager.GetString("FirstNameValidatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lastname must be between 1 and 100 characters.
        /// </summary>
        internal static string LastNameValidatorLength {
            get {
                return ResourceManager.GetString("LastNameValidatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password confirmation may not be empty.
        /// </summary>
        internal static string PasswordConfirmationValidatorNonEmpty {
            get {
                return ResourceManager.GetString("PasswordConfirmationValidatorNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain at least 5 characters.
        /// </summary>
        internal static string PasswordValidatorLength {
            get {
                return ResourceManager.GetString("PasswordValidatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password may not be empty.
        /// </summary>
        internal static string PasswordValidatorNonEmpty {
            get {
                return ResourceManager.GetString("PasswordValidatorNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be the same as the confirmation password.
        /// </summary>
        internal static string PasswordValidatorSameAs {
            get {
                return ResourceManager.GetString("PasswordValidatorSameAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user must at least have one role.
        /// </summary>
        internal static string RolesValidatorNotEmpty {
            get {
                return ResourceManager.GetString("RolesValidatorNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username must be between 1 and 50 characters.
        /// </summary>
        internal static string UserNameValidatorLength {
            get {
                return ResourceManager.GetString("UserNameValidatorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username may not be empty.
        /// </summary>
        internal static string UserNameValidatorNonEmpty {
            get {
                return ResourceManager.GetString("UserNameValidatorNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The website url must be between 1 and 100 characters.
        /// </summary>
        internal static string WebsiteValidatorLength {
            get {
                return ResourceManager.GetString("WebsiteValidatorLength", resourceCulture);
            }
        }
    }
}
