//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuyahoga.Web.Admin {
    
    public partial class Categories {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.HyperLink btnNewRoot;
        protected System.Web.UI.WebControls.Literal litNoRoot;
        protected System.Web.UI.WebControls.RadioButtonList rdioListRoot;
        protected System.Web.UI.WebControls.Repeater rptCategories;
        protected System.Web.UI.WebControls.Button btnMove;
        protected System.Web.UI.WebControls.DropDownList ddlMoveCategories;
    }
}
