//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuyahoga.Modules.Search {
    
    public partial class Search {
        protected System.Web.UI.WebControls.Panel pnlCriteria;
        protected System.Web.UI.WebControls.TextBox txtSearchText;
        protected System.Web.UI.WebControls.Button btnSearch;
        protected System.Web.UI.WebControls.Panel pnlFilter;
        protected System.Web.UI.WebControls.Label lblFilter;
        protected System.Web.UI.WebControls.LinkButton lnkBtnRemoveFilter;
        protected System.Web.UI.WebControls.Panel pnlResults;
        protected System.Web.UI.WebControls.Label lblFrom;
        protected System.Web.UI.WebControls.Label lblTo;
        protected System.Web.UI.WebControls.Label lblTotal;
        protected System.Web.UI.WebControls.Literal litFor;
        protected System.Web.UI.WebControls.Label lblQueryText;
        protected System.Web.UI.WebControls.Label lblDuration;
        protected System.Web.UI.WebControls.Repeater rptResults;
        protected Cuyahoga.ServerControls.Pager pgrResults;
        protected System.Web.UI.WebControls.Panel pnlNotFound;
    }
}
